### PR TITLE
Validate date before changing filter state (#14)

### PR DESCRIPTION
**Pull request by blms**
## In this PR

- Per #14:
  - Style month range inputs
  - Allow cross-browser keyboard control (up/down arrow keys) of the month range inputs
  - Validate input before changing the filter state

## Questions

- Is my approach in 39c51832d5f424aca52412cc7672a05ed113d6c2 decent? It technically works, but it raises a warning about updating the state for one component (`AuthorSelect`) in a different component (`MonthRangeInput`) when you change the date filter. I also don't like having to synchronize the filter state manually with the input state, nor mixing the two as in [this line](https://github.com/performant-software/itsb/blob/39c51832d5f424aca52412cc7672a05ed113d6c2/src/components/MonthRangeInput/MonthRangeInput.jsx#L35), but I don't know how else to handle invalid input while still allowing users to type in the date manually in browsers that don't support the `month` input type.
  - In the prior implementation (i.e. current `main`), typing any invalid dates in the field on Firefox or Safari throws an error and breaks everything. The goal here is to allow users with those browsers to manually type in the date, which may result in temporarily invalid/incomplete dates, so we need to handle those somehow.
  - If you want to try playing around with other approaches, you can check out 9d46939d637ccc4074be8151f91b97afb156b914 and still get the benefit of the new styles and keyboard input handling.
- I noticed a strange bug that appears to be present in current `main` as well: changing the start date successfully updates the filter state and filters the results by date, but changing the end date does not. Any idea why?

### CODE REVIEW

**Comment by blms** [comment]
@rsimon After sleeping on it… Maybe a simpler approach would be if we left the filter state and the input state combined, but ensure that the filter doesn't break on bad input, instead just throwing some kind of handleable error and retaining the prior filter state. Let me know if that sounds more reasonable and I can give it a try.

**Review by rsimon — APPROVED** [review]
I don't see anything wrong with the current approach. On the contrary: IMO filter state, as a fundamental state var in the application, should always be valid. If there's a UI component that could be in invalid state, it should be the responsibility of that component to maintain it's own state, and then only pass valid states "upward" to the application.

We could think about encapsulating validation into a separate sub-component, say "ValidatingMonthInput" or something, which would then only trigger a `onChange` prop handler when the user has entered a valid value. It probably wouldn't save us much repetition, though. At least not if we want to keep the joint help warning that's displayed when any of those inputs are invalid. (In which case the sub-component would also need to trigger something like an `onInvalidEntry` handler; and `MonthRangeInput` would have to maintain `valid` / `invalid` state all over again...)

> It technically works, but it raises a warning about updating the state for one component (`AuthorSelect`) in a different component (`MonthRangeInput`) when you change the date filter. 

Can you explain/point where this happens? Do you mean there's a cross-dependency between AuthorSelect and MonthRange input? I don't see any, TBH. The both manipulate the `filters` field of the search, that's true. But each component will only touch it's own filter (the one wit `name: 'authors'` or `name: 'daterange'`, respectively).

**Comment by rsimon** [comment]
BTW: two more questions:

- Was it a specific requirement to replace the date range slider from the original site with a month input? (The slider seems like a quicker option. On the other hand, the manual input is better for users who want to look at a specific date range.)
- I noticed that I can use keyboard input in FF, but not in Chrome. Should we look into using a calendar widget from a React component library instead, perhaps?

**Comment by blms** [comment]
Thanks @rsimon for the excellent feedback. Glad to hear the approach is generally sound.

> What we could maybe consider is to encapsulate the validation into a separate sub-component, say `ValidatingMonthInput` or something. 

I'm fine leaving it as is unless you feel strongly about this.

> And also if we want to, perhaps, trigger a warning if the end date is before the start date.

I think we should do this regardless!

> Can you explain/point where this happens? Do you mean there's a cross-dependency between AuthorSelect and MonthRange input?

Strangely, I thought this was the warning I was getting, but maybe I'd misread, as I'm getting a different warning now (unrelated to AuthorSelect). And it only occurs when I use the button controls, so maybe there's something else happening here. I'll look into it further!

https://user-images.githubusercontent.com/7234006/199513385-064f9d88-e0df-47e3-b0f5-02f16478c602.mov

> Was it a specific requirement to replace the date range slider from the original site with a month input? (The slider seems like a quicker option. On the other hand, the manual input is better for users who want to look at a specific date range.)

Yes, it was required that a user be able to select specific month/year combinations by typing or clicking up/down buttons. It wasn't a requirement that we use `input type="month"` but I thought it was the most suitable element.

> I noticed that I can use keyboard input in FF, but not in Chrome. Should we look into using a calendar widget from a React component library instead, perhaps?

I was wondering that too; I tried to find a polyfill for `input type="month"` that would work cross-browser, but I only found [this one](https://github.com/LogicamenteInfo/input-month-polyfill) and it seemed to not be well-maintained. Could be worth using if you're having trouble with my implementation, though.

I actually just also found [this one](https://github.com/optimify-studio/react-month-picker-input), which seems like a simple and elegant solution. Worth switching to this?

Can you describe what happens in Chrome? By keyboard input, do you mean typing month/year, or using up/down arrow keys when the input is focused?

**Comment by rsimon** [comment]
Ok, looks like there's some weird race condition stuff going on. I just got "Cannot update a component (ITSBSearchHandler) while rendering a different component (MonthRangeInput)". I'll also dig...

**Comment by rsimon** [comment]
I can see what's going on. Maybe we need to untangle a bit after all, concerning syncing between component and search state. So, the root problem is this: you are updating the search state (using `setFilter`) as a side-effect inside the state update (`setMonthInputValue`). This seems to cause a race condition, where components are concurrently updated because of the search state update, and the local state update.

The way to resolve this would be to __only__ update the local state first. Then, use an effect to propagate the local change to the search state, if the local state is valid. Something like:

```js
useEffect(() => {
  if (isValid(monthInputValue.to) && isValid(monthInputValue.from)) {
    setFilter(...);
  }
}, [ monthInputValu]);
``` 

This is currently a bit complicated by the fact that the local state stores the string representation, whereas the filter expects a `Date` type. My preference would be to change things, so that the filter __also__ works with the string representation, I think. This way, we would have a straightforward option in the future, should we ever want to serialize our filter settings into a share-able URL.

Let me know if you need help with this. I can look into this tomorrow (European) morning.

**Comment by rsimon** [comment]
P.S.: weirdly enough, I'm only getting the warning the first time I'm changing the date filter setting (in Chrome at least). Seems to work fine on subsequence increments.

**Comment by blms** [comment]
Thanks, I'll try `useEffect`! Good call about updating that within the setState callback, that's definitely a likely culprit.

> This is currently made a bit complicated by the fact that the local state is using the string representation YYYY-MM, whereas the filter expects a Date. My preference would be to change things, so that the filter also works with the string representation, I think. This way, we would have a straightforward option in the future, should we ever want to serialize our filter settings into a share-able URL.
> 
> Let me know if you need help with this. I can look into this tomorrow (European) morning.

I agree it would be better if both use the string representation. I'll see how far I can get and let you know.

**Comment by rsimon** [comment]
> Can you describe what happens in Chrome? By keyboard input, do you mean typing month/year, or using up/down arrow keys when the input is focused?

Up and down arrow keys work fine. But, yes, the typing didn't work for me. However, now that I played with it: Chrome's default behavior is actually quite nice. Although it blocks text entry in the way we planned, it does let you select & highlight month and year individually. Then, depending on what's selected, you can either increment/decrement month or year (up/down keys); or you can type. If you type while the month is selected, you get (localized) autocomplete for months. For years, you can simply enter the year.

**Comment by rsimon** [comment]
Ahm... nope. That one's on me ;-) A pretty stupid bug in my waypoint sorting code. Fix upcoming!

**Comment by blms** [comment]
Thanks for the quick fix @rsimon! I think we're almost there, but something is still not quite right in `sortWaypoints`:

https://user-images.githubusercontent.com/7234006/199562930-f916c09d-02fd-4bee-aec9-9b80c0ce66d1.mov

**Comment by rsimon** [comment]
Ok weird. I get that drop out at 1972, but the apart from that it's fine. I'll investigate.

**Comment by blms** [comment]
I see, thank you very much for this late in the day fix @rsimon! That makes a lot of sense that the traversal would fail on out-of-sequence waypoints. It's working now, so I'll go ahead and merge. I'll also open an issue about date-sorted waypoints.

**Pull request merged**
