### PR TITLE
9 intersections sidebar

### PR DESCRIPTION
**Pull request by rsimon**
## In this PR

- As per #9 and #13 
  - Adds a sidebar to the intersections view that lists author waypoints at this place, according to the current filter settings
  - Introduces a bit of refactoring to the utility methods (including those used to calculate presence likelihood), which are now all associated with the `ITSBStore` component
  - Change the main page layout CSS to a `flex`-based approach, so we can display the `MapPage` in either two-column or three-column mode (for itineraries and intersections, respectively)

## Questions/issues
- When switching between itinerary and intersection views, the map layers shift away from their correct positions. The effect goes away as soon as the map is panned/zoomed. I haven't yet figured out how to force a programmatic redraw after the size of the map window changes.
- As discussed, there's a weird time lag between clicking the map and the `onClick` handler getting called

### CODE REVIEW

**Review by blms — CHANGES_REQUESTED** [review]
This is looking really good so far!

I made a couple of tweaks, mostly to CSS to fix an issue where I wasn't able to get the right panel to scroll.

I think I have a possible solution for the map switching, but it would have to take place in Peripleo:

```jsx
// src/map/components/Map/MapLibreDeckGL/DeckGLContainer.tsx

useEffect(() => {
  if (ref.current) {
    setCurrentViewState(getDefaultViewState(props.defaultBounds, ref.current));
  }
}, [props.layers]);
```

Something like this. At least, the view state needs to be updated at some point when the layers change.

There's a bit of a strange lag for this as well, so maybe I'm not doing this at exactly the right place. If the lag is unavoidable, a loading indicator (or some way to tell the consumer application that loading is in progress) would be very helpful.

Can merge once this is resolved!

(BTW, is there a plan ahead for publishing Peripleo on npm or elsewhere so that we can consume it without needing to pull updates locally?)

**Comment by blms** [comment]
Also: I'll take a crack at handling the lag for the `onClick` handler in a separate branch once this is merged, using Deck.GL's other kind of [recommended click handling](https://deck.gl/docs/developer-guide/interactivity#calling-the-picking-engine-directly).

**Comment by rsimon** [comment]
Hi Ben, 

sorry for the delay. (I was kept a bit busy with other projects this week...) Thanks for looking into a solution for the map switching. The good news: I could resolve the lag - see below. (There are some bad news further down below, too.)

```
useEffect(() => {
  if (ref.current) {
    setInitialViewState(getDefaultViewState(props.defaultBounds, ref.current));
  }
}, [props.layers]);
```

Updates to the DeckGL map state generally work by setting the `initialViewState`. The `currentViewState`, on the other hand, is debounced and synced "upwards" to Recoil, and then goes back "down" into the map component. If you set the initial state directly, the lag is gone.

The obvious benefit of this approach is that you can manipulate the map state from the outside, via Recoil. Intuitively, it should be possible to omit the local `initialViewState` altogether, and use only the Recoil-managed `currentViewState`. However, Recoil always introduces the lag. I have fought with this problem in another context already, and was, frankly, unable to understand it completely. (The debouncing is not the issue, BTW.)

Anyways: I commited the change to the Peripleo repo. The lag should now be gone.

The bad news: because the code snippet will reset the map to the default view (= the bounds configured in the `<Peripleo>` tag), the map viewport state gets lost when switching between Trajectories and Itineraries.

I have not found a solution to this problem yet. Just resetting the map the `currentViewState` doesn't change anything; any access to the map's internal vanilla JS API (which has a .redraw() method) seems to fail.

**Comment by rsimon** [comment]
> (BTW, is there a plan ahead for publishing Peripleo on npm or elsewhere so that we can consume it without needing to manually pull updates locally?)

Yes - definitely! I was planning to publish a version 0.1.0 as soon as first version of ITSB is complete, so we have a solid release.

**Comment by blms** [comment]
Hi Rainer, thanks for all your work on this!

I just pushed a change with some fixes to the non-map content pages; I noticed now that they weren't able to scroll! (Actually pushed a really hacky solution then realized an extremely simple one immediately after 😆 )

> Anyways: I commited the change to the Peripleo repo. The lag should now be gone.

I pulled the latest from Peripleo but I still seem to be getting some lag (maybe less than before? if so then I think it's fine). I did notice that I'm being reset to the default view state on each click, which makes it rather cumbersome to use:

https://user-images.githubusercontent.com/7234006/201217287-a766d690-e287-4f37-9415-81922896c8ca.mov

> The bad news: because the code snippet will reset the map to the default view (= the bounds configured in the <Peripleo> tag), the map viewport state gets lost when switching between Trajectories and Itineraries.

A quick thought: I think it's actually fine to lose all state between the two. They are treated as two separate "pages"/visualizations in the original app, and there was not even an option to choose authors on the intersections viz. In fact, I'd be fine with removing that altogether or setting all authors selected by default for intersections.

> Yes - definitely! I was planning to publish a version 0.1.0 as soon as first version of ITSB is complete, so we have a solid release.

Great!

**Comment by rsimon** [comment]
Hi Ben,

I made [another commit to Peripleo](https://github.com/peripleo/peripleo/commit/ee21fea8c0273f9d9a298f41277fdcd174cceb33) which fixes the above issue. The map no longer resets on selection. The problem was (of course...) our dirty hack to reset the map whenever the layers would change. I now changed this to use a resize observer. This way, the map only resets when it resizes (which is what we want).

Personally, I think it's still not _quite_ clean. 
- The map will also reset if the user just resizes the browser window, not only when they toggle Trajectories/Intersections
- Technically, I guess, map state should be retained between toggles, because the map component doesn't actually un-mount. (I wonder if there's a way to force it to unmount temporarily through React Router?)

I'll play a bit more with the problem. It's turning out to be a tricky one... there's clearly something happening inside DeckGL we can't control. Or perhaps it has to do with using MapLibre rather than MapBoxGL, since the DeckGL layers seem to behave fast and correct, while the underlying basemap fails to update position.

Concerning the remaining lag: yes, there's still some lag, but it's at least much less in my case. Also seems to be related to some kind of disconnect between the DeckGL layer and the basemap.

**Comment by rsimon** [comment]
Another [commit to Peripleo](https://github.com/peripleo/peripleo/commit/f472c3a83682b7f7ac0bf450dcf27f1d078be9c7): the map now retains state on resize. I think that's the technically more correct solution (because React Router doesn't actually unmount). But we can roll back if we want to.

It's a bit wild, in a way. Because it needs to regenerate the ResizeObserver whenever the viewport changes. Doesn't seem to add much overhead though (since the observer isn't actually used, except when the container element is resized); and the viewport changes are debounced.

There's still the same - small, but noticable - jump (and a bit of visible stretch) when toggling. But this is probably as close as we get. IMO the only alternative solution would be to avoid resizing of the map altogether, and instead display intersection data as an overlay or something?

**Comment by rsimon** [comment]
Another update for today: I figured out how to do patch that alternative onClick approach into Peripleo - and it does indeed work faster! Commits are on the way.

**Review by blms — APPROVED** [review]
Great improvements all around! Super fast, everything works as expected with every interaction I tested. I'm fully satisfied with how this is working now, so feel free to merge (unless you wanted to make additional changes first).

**Pull request merged**
